# Generated by Django 4.2.16 on 2025-07-03 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrolled_users",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
